services:
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - 55000:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  pgadmin:
    image: dpage/pgadmin4:8.12
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - postgres