INSERT INTO "actor" ("name", "bio", "image_path")
VALUES ('Ertl Zsombor', 'Ertl Zsombor Budapesten született. Gyerekkora óta vonzotta az előadóművészet, hiszen már tíz évesen kis Oresztészként szerepelt a Novák Ferenc rendezte Magyar Elektrában. 2015-ben érettségizett a Kodály Zoltán Magyar Kórusiskolában, és gimnáziumi évei alatt három éven tagja volt a Katona Klubnak. Ezt követően felvételt nyert a Színház- és Filmművészeti Egyetemre, ahol 2020-ban végzett Marton László, Hegedűs D. Géza és Forgács Péter osztályában. Egyetemi gyakorlatát a Vígszínházban töltötte, majd a diploma megszerzése után a társulat tagja lett.', 'https://www.vigszinhaz.hu/res/imgcache/vig_21_tarsulat_honlap_610x406px_ertl_rb_610x610.jpg'),
       ('Dino Benjamin', '1996-ban született Királyhelmecen, a helyi gimnáziumban érettségizett. 2020-ban szerzett diplomát a Színház- és Filmművészeti Egyetemen Marton László, Hegedűs D. Géza és Forgács Péter osztályában. Egyetemi gyakorlatát a Vígszínházban töltötte, 2020 óta társulati tag.', 'https://www.vigszinhaz.hu/res/imgcache/vig_21_tarsulat_honlap_610x406px_dino_rb_610x610.jpg'),
       ('Marton László', 'Marton László (Budapest, 1943. január 6. – Budapest, 2019. szeptember 12.) Kossuth- és Jászai Mari-díjas magyar színházrendező, színigazgató, érdemes és kiváló művész. Rendezéseit 2017-ig több mint 40 országban játszották világszerte. 2017-ben szexuális zaklatási ügyekben léptek fel ellene, ezután felmentették állásaiból, később visszavonult a közélettől.', 'https://media.fidelio.hu/2019/09/12/18611373_f60c7ce184a8d1689bfb4f9b97516deb_o-%5B1568281068%5D.png/1198'),
       ('Fesztbaum Béla', 'Fesztbaum Béla Egerben született. 1989-1993-ig a szentesi Horváth Mihály Gimnázium irodalmi-drámai tagozatán tanult. 1993-1997-ig a Színház- és Filmművészeti Egyetem színművész hallgatója volt, Marton László osztályában. 1997 óta a Vígszínház társulatának tagja.', 'https://www.vigszinhaz.hu/res/imgcache/vig_21_tarsulat_honlap_610x406px_fesztbaum_rb_610x610.jpg'),
       ('Szirtes Tamás', 'Színház- és Filmművészeti Főiskola 1968, 1968 - 1972. József Attila Színház - rendező, 1972 - 1973. Miskolci Nemzeti Színház - rendező, 1973 - Madách Színház - rendező, 1977-2005. a Színház és Filmművészeti Főiskola egyetemi docens, 2004. február 1. - a Madách Színház Nonprofit Kft. ügyvezető igazgatója', 'https://i.madachszinhaz.hu/szirtes-tamas.inbox732x732.webp'),
       ('Auksz Éva', 'Színház és Filmművészeti Egyetem 2016.', 'https://i.madachszinhaz.hu/auksz-eva.inbox732x732.webp'),
       ('Jenővári Miklós', 'Színház- és Filmművészeti Egyetem 2019.', 'https://i.madachszinhaz.hu/jenovari-miklos.inbox732x732.webp'),
       ('Botos Éva', 'Színészi pályafutását az Arany János Színháznál kezdte 1992-ben, hat évvel később diplomázott a Színház- és Filmművészeti Főiskolán, osztályvezető tanára Benedek Miklós volt. Játszott az Új Színházban és a Centrál Színházban is, 2016 óta szabadúszó. A színészet mellett énekesnőként is aktív.', 'https://i.madachszinhaz.hu/botos-eva-1.inbox366x366.jpg'),
       ('Horgas Ádám', 'Horgas Ádám (Budapest, 1969. március 12. –) magyar színész, rendező, táncos, koreográfus, zeneszerző és író. Előszeretettel hoz létre összművészeti produkciókat. Az Atlantis Színház alapítója és művészeti vezetője. A Mab című első magyar web-thrillersorozat kitalálója és alkotója, mely után megszervezte az első országos websorozat portált, pályázatot és fesztivált.', 'https://www.szinhaz.szeged.hu/sites/default/files/styles/tarsulat/public/content/tarsulat/horgas_adam.jpg?itok=pSdYvk2g'),
       ('Gáspárfalvi Dorka', 'Gáspárfalvi Dorka (Budapest, 2002. szeptember 28. –) magyar színésznő, artista, kaszkadőr, szinkronszínész.', 'https://ocdn.eu/pulscms/MDA_/24b1aad9fbc0a5f8e30c9930180c8a2f.jpg'),
       ('Hegedűs D. Géza', 'Hegedűs D. Géza (eredetileg Hegedűs Géza, Ibrány, 1953. május 7. –) a Nemzet Színésze címmel kitüntetett, Kossuth- és Jászai Mari-díjas magyar színművész, rendező, egyetemi docens, érdemes és kiváló művész a Színház- és Filmművészeti Egyetem volt rektorhelyettese, a MASZK Országos Színészegyesület elnöke, továbbá a Magyar Színházi Társaság elnökségének és a Nemzeti Előadó-művészeti Érdekegyeztető Tanácsnak (NEÉT) tagja, a Halhatatlanok Társulatának örökös tagja, a Vígszínház egykori MSZMP-titkára.', 'https://pb2.jegy.hu/imgs/system-4/program/000/084/612/hegedus-d-geza-bemutatja-a-nemzet-szineszeit-original-99767.jpg'),
       ('Kövesi Zsombor', 'Kövesi Zsombor Győrben született. 2017-ben kezdte színházi tanulmányait a Színház- és Filmművészeti Egyetemen, ahol 2022-ben szerzett diplomát Székely Kriszta és Máté Gábor osztályában. Egyetemi gyakorlatát a Vígszínházban töltötte, majd 2022-ben a társulat tagja lett.', 'https://www.vigszinhaz.hu/res/imgcache/kovesi-zsombor_vig_2022_tarsulati-portrek_emmer-laszlo_web_01_rb_610x610.jpg'),
       ('Borbiczki Ferenc', 'Győrben született. 1981-ben szerzett diplomát a Színház- és Filmművészeti Főiskolán, majd ugyanebben az évben leszerződött a Veszprémi Petőfi Színházhoz. Tíz évig játszott a királynék városában, számtalan emlékezetes alakítása emelte őt a nyolcvanas évek legendás veszprémi színészévé.', 'https://www.vigszinhaz.hu/res/imgcache/vig_21_tarsulat_honlap_610x406px_borbiczki_rb_610x610.jpg'),
       ('Kovács Patrícia', 'Budapesten született, 2003-ban végzett a Színház- és Filmművészeti Egyetemen, Máté Gábor osztályában. Ezt követően 2007-ig az egri Gárdonyi Géza Színház tagja, 2009-től a Vígszínház színművésze. 2011-2017 között szabadúszóként dolgozott, majd az Orlai Produkciós Iroda társulatának tagja lett. 2021-től ismét a Vígszínház művésze.', 'https://www.vigszinhaz.hu/res/imgcache/vig_21_tarsulat_honlap_610x406px_kovacs_rb_610x610.jpg'),
       ('Ötvös András', 'Ötvös András Székesfehérváron született. 2007-ben végzett a Színház- és Filmművészeti Egyetemen Máté Gábor és Horvai István osztályában. Egyetemi hallgatóként A karnevál utolsó éjszakája című előadásban játszott főszerepet, amit a Katona József Színházban mutattak be.', 'https://www.vigszinhaz.hu/res/imgcache/otvos-andras_vig_2022_tarsulati-portrek_emmer-laszlo_web_01_rb_610x610.jpg'),
       ('Vajna Levente', 'Ez én vagyok, easter egg.', 'https://scontent-fra3-2.xx.fbcdn.net/v/t39.30808-6/441460362_2119154528463422_1791968095881326428_n.jpg?stp=cp6_dst-jpg_tt6&_nc_cat=111&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=k1ajNAvHljwQ7kNvgF5FUPk&_nc_zt=23&_nc_ht=scontent-fra3-2.xx&_nc_gid=A49ugPjpH0gkrRAluws3JN9&oh=00_AYDTz_P7_YabUKBMw99W6Ek0NFIo3bFjd6XR7OMfnqz7sA&oe=67602277');

INSERT INTO "dramas" ("title", "genre", "duration", "description", "image_path", "director_id") VALUES
        ('Mellékhatás', 'Drama', 90, 'A modern orvostudomány felkent papjai a gyógyszergyárak kutatóorvosai. Connie és Tristan, egy új antidepresszáns fiatal tesztalanyai keresnek választ az égető kérdésre, vajon egymás iránti érzelmeik természetes vonzódásból erednek vagy a gyógyszer korbácsolja fel őket? Mit tehet értünk az orvostudomány, és hol vannak a beavatkozás határai?', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgqFBQ2PB9IDkv-HMZVayQYGqnCZ99bouyaw&s', 9),
        ('Pál utcai fiúk', 'Drama', 170, 'A magyar irodalom egyik legszívbemarkolóbb alkotása felnőtteket, fiatalokat egyaránt megérint. Közös gondolkodásunk és közbeszédünk része lett a grund, amely a miénk, ahogy azt Dés-Geszti csupa érzelem, csupa dallam betétdalában éneklik a szereplők. Mindnyájan emlékszünk az einstandolásra, a gittegyletre, a füvészkertre, a csatára a grundon, és Nemecsek megrázó önfeláldozására. Költészettel és emlékekkel teli hívószavak ezek, Molnár Ferenc legendás regényéből, amelyet minden generáció újra és újra felfedez magának.', 'https://marvin.bline.hu/product_images/35/ID22-297208.JPG', 3),
        ('Mary Poppins', 'Musical', 170, '„Az égen minden csillag néked ragyog,Megtörténhet bármi, hogyha hagyod...” énekli a musical címszereplője. Mary Poppins mágikus erejű figuráját, a gyerekirodalom felejthetetlen dadusának alakját az ausztráliai születésű angol Pamela Lyndon Travers, újságíró, színésznő, táncosnő találta ki. Évtizedeken át írta, regénnyé, sőt regénysorozattá formálta az epizódokat, még 90 évesen is dolgozott rajta. 1964-ben film, majd 2004-ben Travers történetei és a film alapján színpadi musical született. A szövegkönyvet Julian Fellowes készítette, a zenét Richard M. Sherman és George Stiles szerezte, a dalszöveget Robert B. Sherman és Anthony Drewe írta. Azóta a világ színpadairól levehetetlen, rengeteg díjat nyert sikerdarabbá vált, felnőttek és gyerekek gyönyörűségére. A siker titka az az utánozhatatlan báj, amellyel a musical egybeötvözi a környező világ hétköznapjait a tündérmesék varázslatával...', 'https://www.musicalinfo.hu/keptar_cikkek/2166.jpg', 5),
        ('Dzsungel könyve', 'Adventure', 150, 'Ugyan ki tudná összefoglalni, mi mindenről szól a farkasok közt nevelkedett Maugli, az emberek ketrecéből szabadult Bagira, a törvényt bölcsen oktató Balu, a titokzatos Ká, a bosszúra és embervérre szomjas Sír Kán története? Szól a születésről és a halálról, a befogadásról és a kitaszításról, a csapatról és a magányról, a gyerekkor és a kamaszkor varázslatos időszakáról — vagyis mindarról, ami egy "kölyökkel" megeshet, akár farkasok, akár emberek között nevelkedik.', 'https://turayidaszinhaz.hu/wp-content/uploads/2015/10/dzsungel_honlap_belso.jpg', 11);
